server:
  port: 8089

kafka:
  topics:
    new-load-events: new-load-events-topic
    s3-load-events: s3-load-events-topic
    s3-load-notfnd-events: s3-load-notfnd-events-topic
    db-update-events: db-update-events-topic
    sample-events: sample-events-topic
